CREATE TABLE noteful_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    folder_id INTEGER
        REFERENCES noteful_folders(id) ON DELETE CASCADE NOT NULL,
    note_name TEXT NOT NULL,
    note_content TEXT,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);